services:
  worker:
    image: python-flask-api:latest
    hostname: flask-api-worker
    command: celery -A celery_worker worker --loglevel=info --concurrency=2
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./tasks:/app/tasks
      - ./celery_worker.py:/app/celery_worker.py
      - ./conf:/app/conf
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: unless-stopped

  beat:
    image: python-flask-api:latest
    hostname: flask-api-beat
    command: celery -A celery_worker beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./tasks:/app/tasks
      - ./celery_worker.py:/app/celery_worker.py
      - ./conf:/app/conf
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
